apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-aws
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-aws
  template:
    metadata:
      labels:
        app: app-aws
    spec:
      containers:
      - name: app-aws
        image: 022694873939.dkr.ecr.eu-west-3.amazonaws.com/flask-web-app:latest

        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: app-aws
spec:
  selector:
    app: app-aws
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer